// The Slate API for the code editor: completion lists and hover help.
// name -> [signature, what it does]. Module members are "Module.member".

export const API: Record<string, [string, string]> = {
  // drawing
  cls: ["cls(color)", "화면 전체를 한 색으로 지운다"],
  spr: ["spr(name, x, y, { frame, anim, scale, sx, sy, rot, ox, oy, flipX, flipY, alpha, tint, add })", "스프라이트를 그린다. anim = 태그 이름이면 애니메이션"],
  rect: ["rect(x, y, w, h, color)", "채운 사각형"],
  rectline: ["rectline(x, y, w, h, color)", "사각형 테두리"],
  line: ["line(x0, y0, x1, y1, color)", "선"],
  circ: ["circ(x, y, r, color, filled?)", "원"],
  text: ["text(s, x, y, color, { align, scale, outline, font })", "글자. 효과가 필요하면 Text.draw"],
  textw: ["textw(s, scale?, font?) -> width", "글자 폭 (픽셀)"],
  texth: ["texth(scale?, font?) -> height", "줄 높이"],
  textsize: ["textsize(s, scale?, font?) -> w, h", "그려질 글자의 크기. 한글이 섞인 줄은 높이 14 (상자 가운데 정렬용)"],
  wrap: ["wrap(s, width, scale?, font?) -> lines", "단어 단위 줄바꿈"],
  font: ['font("erx" | "erx_b" | "erx_gl" | "pico") -> previous', "기본 글꼴 바꾸기"],
  camera: ["camera(x?, y?)", "이후 그리기를 (x, y)만큼 밀어서 그린다. 인자 없이 = 원래대로"],
  blend: ['blend("add" | nil)', "더하기 합성 (빛, 불꽃)"],
  sprite: ["sprite(name) -> { w, h, frames, fps, tags, durations, box }", "스프라이트 정보"],
  hitbox: ["hitbox(name, x, y, { flipX, ox, oy }) -> { x, y, w, h }", "픽셀 에디터에서 그린 충돌 박스를 그 위치에 맞춰서 (없으면 스프라이트 전체)"],
  // maps
  map: ["map(name, x, y, { layer, tint })", "타일맵 그리기"],
  mget: ["mget(map, tx, ty, layer?) -> tile", "칸의 타일 값 (-1 = 빈칸)"],
  mset: ["mset(map, tx, ty, tile, layer?)", "칸의 타일 바꾸기"],
  mapinfo: ["mapinfo(map) -> { w, h, tw, th, tilesets }", "맵 크기(칸)와 타일 크기(픽셀)"],
  msolid: ["msolid(map, px, py, bit?) -> bool", "그 픽셀 위치의 타일이 단단한지 (플래그 bit, 기본 0)"],
  fget: ["fget(tileset | map, tile, bit?) -> bool", "타일 플래그"],
  objects: ["objects(map, type?) -> { { id, type, sprite, x, y, props... } }", "맵 에디터에서 놓은 오브젝트 (x, y = 아래 가운데)"],
  playtest: ["playtest() -> { map, x, y } | nil", '"Play from here"로 실행했을 때 시작 위치'],
  // input
  btn: ["btn(action) -> bool", "누르고 있는 동안: left right up down a b x y start select (키보드 + 패드 + 터치)"],
  btnp: ["btnp(action) -> bool", "이번 프레임에 눌렀을 때"],
  bind: ['bind(action, { "z", "space", "pad_a" })', "행동에 키 묶기"],
  axis: ['axis("x" | "y" | "rx" | "ry" | "lt" | "rt") -> -1..1', "아날로그 입력"],
  pad: ["pad() -> name | nil", "연결된 게임패드 이름"],
  key: ["key(name) -> bool", "키를 누르고 있는지"],
  keyp: ["keyp(name) -> bool", "키를 이번 프레임에 눌렀는지"],
  mouse: ["mouse.x  mouse.y  mouse.down  mouse.pressed  mouse.released  mouse.wheel  mouse.right  mouse.rpressed  mouse.long  mouse.held", "마우스 (게임 좌표). long = 0.5초 길게 누름 (터치 화면의 우클릭), rpressed = 우클릭"],
  tr: ['tr(key, vars?) -> text', 'lang/<언어>.json의 문장. tr("gold", { n = 3 })은 "{n}"을 채운다'],
  lang: ['lang(code?) -> code', '지금 언어, lang("en")으로 바꾸기 (다음 실행에도 기억)'],
  langs: ["langs() -> { codes }", "lang/ 폴더에 있는 언어들"],
  seed: ["seed(n)", "같은 n이면 rnd / irnd / pick 순서가 같다 (리플레이, 테스트)"],
  quit: ["quit(code?)", "게임 종료 (데스크톱). 자동 테스트가 끝날 때 결과 코드로"],
  hit: ["hit(x, y, w, h) -> bool", "마우스가 그 사각형 위에 있는지"],
  // sound
  sfx: ["sfx(name, volume?)", "효과음 (sounds/ 파일 또는 coin jump hit explode powerup click buy error)"],
  music: ["music(name, { volume, loop, fade }) / music(nil, { fade })", "배경음악 재생 / 정지 (크로스페이드)"],
  musicname: ["musicname() -> name | nil", "지금 나오는 음악"],
  beep: ["beep(freq, dur, wave, vol, slide)", "즉석 소리"],
  volume: ['volume("music" | "sfx", v?) -> 0..1', "전체 음량"],
  // system
  fullscreen: ["fullscreen(on?) -> bool", "전체 화면 (F11 / Alt+Enter)"],
  save: ["save(key, value)", "저장 (숫자, 글자, 표)"],
  load: ["load(key, fallback) -> value", "불러오기"],
  wipe: ["wipe(key)", "저장 지우기"],
  log: ["log(...)", "콘솔에 출력"],
  require: ['require("name")', "scripts/의 다른 파일 불러오기"],
  t: ["t() -> seconds", "게임 시작 후 시간"],
  now: ["now() -> seconds", "실제 시각"],
  rnd: ["rnd(a?, b?) -> number", "난수: rnd() 0~1, rnd(n) 0~n, rnd(a, b)"],
  irnd: ["irnd(a, b) -> integer", "a~b 정수 난수"],
  pick: ["pick(list) -> item", "목록에서 하나"],
  clamp: ["clamp(v, lo, hi)", "범위 안으로"],
  lerp: ["lerp(a, b, k)", "a와 b 사이"],
  fmt: ["fmt(n) -> string", "큰 수: 1234 -> 1.23K"],
  W: ["W", "화면 폭"],
  H: ["H", "화면 높이"],
  init: ["function init()", "시작할 때 한 번"],
  update: ["function update(dt)", "1초에 60번 (dt = 1/60)"],
  draw: ["function draw()", "그리기"],

  // standard library
  Anim: ["Anim.new(sprite, tag?)", "애니메이션 재생기: :play(tag, { loop, onEnd }) :update(dt) :draw(x, y, opts)"],
  "Anim.new": ["Anim.new(sprite, tag?) -> anim", "anim:play(tag) anim:update(dt) anim:draw(x, y) anim.frame anim.done"],
  Timer: ["Timer", "타이머"],
  "Timer.after": ["Timer.after(sec, fn) -> handle", "sec초 뒤에 fn"],
  "Timer.every": ["Timer.every(sec, fn, count?) -> handle", "sec초마다 fn (count번)"],
  "Timer.cancel": ["Timer.cancel(handle)", "타이머 취소"],
  Tween: ["Tween", "값을 부드럽게 바꾸기"],
  "Tween.to": ["Tween.to(obj, sec, { x = 10 }, { ease, delay, onDone, onUpdate })", "obj의 값을 sec초 동안 목표로"],
  Ease: ["Ease.outCubic(t) ...", "linear, in/out/inOut + Quad Cubic Sine, inBack outBack outElastic outBounce"],
  Scene: ["Scene", "화면 전환 (타이틀, 플레이, 게임오버)"],
  "Scene.add": ["Scene.add(name, { enter, leave, update, draw })", "장면 등록"],
  "Scene.go": ["Scene.go(name, args?, { fade, color })", "장면 바꾸기"],
  Cam: ["Cam", "카메라"],
  "Cam.follow": ["Cam.follow(x, y, dt, { lerp, bounds = map, lookX, lookY })", "부드럽게 따라가기 (bounds = 맵 이름이면 맵 밖은 안 보임)"],
  "Cam.shake": ["Cam.shake(amount, time)", "화면 흔들기"],
  "Cam.apply": ["Cam.apply()", "이후 그리기에 카메라 적용"],
  "Cam.reset": ["Cam.reset()", "카메라 해제 (HUD는 이 뒤에)"],
  "Cam.toWorld": ["Cam.toWorld(sx, sy) -> x, y", "화면 좌표 -> 맵 좌표"],
  Physics: ["Physics", "타일 충돌"],
  "Physics.move": ["Physics.move(box, dx, dy, map, { solid, oneway }) -> { left, right, up, down }", "벽을 뚫지 않고 이동 (box = { x, y, w, h })"],
  "Physics.grounded": ["Physics.grounded(box, map, { solid, oneway }) -> bool", "바닥에 서 있는지"],
  "Physics.overlap": ["Physics.overlap(a, b) -> bool", "두 박스가 닿았는지"],
  Path: ["Path", "길찾기 (벽 = 타일 플래그 0)"],
  "Path.chase": ["Path.chase(box, tx, ty, speed, dt, map, { bit, diagonal }) -> hit, ok", "벽을 돌아서 목표를 쫓아간다"],
  "Path.toward": ["Path.toward(map, x, y, tx, ty, { bit, diagonal }) -> dx, dy, dist", "지금 움직일 방향 (길이 없으면 nil)"],
  "Path.find": ["Path.find(map, x0, y0, x1, y1, { bit, diagonal }) -> { {x, y}, ... } | nil", "경유점 목록"],
  "Path.dist": ["Path.dist(map, x, y, tx, ty, { bit, diagonal }) -> tiles | nil", "걸어서 몇 칸"],
  Particles: ["Particles.new()", "파티클"],
  "Particles.new": ["Particles.new() -> fx", 'fx:burst(x, y, n, opts | "preset") fx:update(dt) fx:draw()'],
  "Particles.preset": ['Particles.preset("name") -> opts', "파티클 편집기에서 만든 설정"],
  Dialog: ["Dialog", "대화창"],
  "Dialog.say": ["Dialog.say(text | { pages }, { name, portrait, onDone })", "대화. 글 안에 {wave}...{/} 효과"],
  "Dialog.ask": ["Dialog.ask(text, { choices }, fn(i))", "선택지"],
  "Dialog.active": ["Dialog.active() -> bool", "대화 중인지 (중이면 게임을 멈춘다)"],
  "Dialog.draw": ["Dialog.draw()", "draw() 맨 끝에"],
  UI: ["UI", "메뉴, 버튼, 게이지, 일시정지"],
  "UI.menu": ["UI.menu(items) -> menu", "menu:update() -> 고른 번호, menu:draw(x, y)"],
  "UI.button": ["UI.button(label, x, y, w, h) -> clicked", "버튼"],
  "UI.bar": ["UI.bar(x, y, w, h, value, max, color)", "게이지"],
  "UI.toast": ["UI.toast(message)", "잠깐 뜨는 알림"],
  "UI.pause": ["UI.pause.update() / UI.pause.draw()", "일시정지 화면 (Esc / Enter / Start)"],
  Text: ["Text", "글자 효과"],
  "Text.draw": ["Text.draw(s, x, y, color, { align, scale, wave, shake, rainbow, bounce, blink, typing, start }) -> done", "효과 있는 글자. 글 안에 {wave}...{/} {#ff0044}...{/}"],
  "Text.width": ["Text.width(s, { scale, font }) -> width", "표시를 뺀 폭"],
  "Text.len": ["Text.len(s) -> count", "표시를 뺀 글자 수"],
  "Text.strip": ["Text.strip(s) -> string", "표시를 뺀 글"],
  Fx: ["Fx", "화면 효과와 셰이더"],
  "Fx.flash": ["Fx.flash(color?, time?)", "번쩍"],
  "Fx.freeze": ["Fx.freeze(time?)", "히트스톱 (잠깐 멈춤)"],
  "Fx.fade": ["Fx.fade(color | nil, time, onDone?)", "그 색으로 어두워지기 / nil이면 다시 밝게"],
  "Fx.tint": ["Fx.tint(color?, amount?)", "화면에 색 덮기"],
  "Fx.effect": ['Fx.effect(name | { name = v }, value, fadeTime?)', "셰이더: crt scanlines vignette aberration bloom grayscale sepia invert brightness contrast saturation hue posterize pixelate wave noise"],
  "Fx.shockwave": ["Fx.shockwave(x, y, { speed, size, strength })", "충격파"],
  "Fx.glitch": ["Fx.glitch(time?, strength?)", "지직거림"],
  "Fx.shader": ["Fx.shader(glsl | nil)", "직접 쓴 셰이더 (main(); uv, Texture, time, resolution)"],
  "Fx.reset": ["Fx.reset()", "효과 전부 끄기"],
};

/** Which string argument of a call takes which kind of name (for completing names in quotes). */
export const NAME_ARGS: [RegExp, "sprites" | "maps" | "sounds" | "music" | "effects" | "scenes" | "particles"][] = [
  [/\b(spr|sprite|hitbox|Anim\.new)\(\s*["'][\w-]*$/, "sprites"],
  [/\b(map|mget|mset|mapinfo|msolid|objects|Physics\.(move|grounded)\([^)]*,\s*|Path\.(find|toward|dist)\()\s*["'][\w-]*$/, "maps"],
  [/\bsfx\(\s*["'][\w-]*$/, "sounds"],
  [/\bmusic\(\s*["'][\w-]*$/, "music"],
  [/\bFx\.effect\(\s*["'][\w-]*$/, "effects"],
  [/\bScene\.go\(\s*["'][\w-]*$/, "scenes"],
  [/\b(Particles\.preset\(|:burst\([^)]*,\s*)\s*["'][\w-]*$/, "particles"],
];

export const EFFECT_NAMES = ["crt", "scanlines", "vignette", "aberration", "bloom", "grayscale", "sepia", "invert", "brightness", "contrast", "saturation", "hue", "posterize", "pixelate", "wave", "noise"];
export const SFX_PRESETS = ["click", "coin", "buy", "error", "hit", "jump", "explode", "powerup"];
