// Generates native/player/src/font.rs from the TypeScript font so both runtimes share glyphs.
// npx tsx tools/gen-font-rs.ts
import fs from "node:fs";
import { GLYPHS } from "../packages/runtime/src/font.ts";

const charLit = (ch: string) => (ch === "'" || ch === "\\" ? `'\\${ch}'` : `'${ch}'`);

let out = "// Generated by tools/gen-font-rs.ts from packages/runtime/src/font.ts - do not edit.\n";
out += "pub const FONT_HEIGHT: usize = 7;\npub const LINE_HEIGHT: f32 = 10.0;\npub const SPACE_WIDTH: f32 = 3.0;\n\n";
out += "/// (char, rows) with '#' = pixel on\npub const GLYPHS: &[(char, &[&str])] = &[\n";
for (const [ch, g] of GLYPHS) {
  out += `    (${charLit(ch)}, &[${g.rows.map((r) => JSON.stringify(r)).join(", ")}]),\n`;
}
out += "];\n";
fs.writeFileSync("native/player/src/font.rs", out);
console.log(`wrote ${GLYPHS.size} glyphs`);
